#!/bin/bash

# Code
cd code
echo $(pwd)
cd CNN_CIFAR10
./../../.python-env/bin/python Training.py
./../../.python-env/bin/python Inference.py
cd ..
cd CNN_FashionMNIST
./../../.python-env/bin/python Training.py
./../../.python-env/bin/python Inference.py
cd MobileNetv3Small_Caltech256
./../../.python-env/bin/python Training.py
./../../.python-env/bin/python Inference.py
cd ..
cd ResNet50_Caltech256
./../../.python-env/bin/python Training.py
./../../.python-env/bin/python Inference.py
cd ..
cd DeepLabv3_COCO
./../../.python-env/bin/python Inference.py
cd ..
cd LRASPP_COCO
./../../.python-env/bin/python Inference.py
cd ..
cd FasterRCNN_COCO
./../../.python-env/bin/python Inference.py
cd ..
cd Yolov8n_COCO
./../../.python-env/bin/python Training_Classification.py
./../../.python-env/bin/python Training_Detection.py
./../../.python-env/bin/python Training_Segmentation.py
./../../.python-env/bin/python Inference_Classification.py
./../../.python-env/bin/python Inference_Detection.py
./../../.python-env/bin/python Inference_Segmentation.py
cd ..
cd Yolov8s_COCO
./../../.python-env/bin/python Training_Classification.py
./../../.python-env/bin/python Training_Detection.py
./../../.python-env/bin/python Training_Segmentation.py
./../../.python-env/bin/python Inference_Classification.py
./../../.python-env/bin/python Inference_Detection.py
./../../.python-env/bin/python Inference_Segmentation.py
cd ..
cd Yolov8m_COCO
./../../.python-env/bin/python Training_Classification.py
./../../.python-env/bin/python Training_Detection.py
./../../.python-env/bin/python Training_Segmentation.py
./../../.python-env/bin/python Inference_Classification.py
./../../.python-env/bin/python Inference_Detection.py
./../../.python-env/bin/python Inference_Segmentation.py
cd ..