#!/bin/bash

# Code
cd code
echo $(pwd)
cd CNN_CIFAR10
python3 Training.py
python3 Inference.py
cd ..
cd CNN_FashionMNIST
python3 Training.py
python3 Inference.py
cd MobileNetv3Small_Caltech256
python3 Training.py
python3 Inference.py
cd ..
cd ResNet50_Caltech256
python3 Training.py
python3 Inference.py
cd ..
cd DeepLabv3_COCO
python3 Inference.py
cd ..
cd LRASPP_COCO
python3 Inference.py
cd ..
cd FasterRCNN_COCO
python3 Inference.py
cd ..
cd Yolov8n_COCO
python3 Training_Classification.py
python3 Training_Detection.py
python3 Training_Segmentation.py
python3 Inference_Classification.py
python3 Inference_Detection.py
python3 Inference_Segmentation.py
cd ..
cd Yolov8s_COCO
python3 Training_Classification.py
python3 Training_Detection.py
python3 Training_Segmentation.py
python3 Inference_Classification.py
python3 Inference_Detection.py
python3 Inference_Segmentation.py
cd ..
cd Yolov8m_COCO
python3 Training_Classification.py
python3 Training_Detection.py
python3 Training_Segmentation.py
python3 Inference_Classification.py
python3 Inference_Detection.py
python3 Inference_Segmentation.py
cd ..